### 배열 생성하기

In [4]:
!pip install numpy

In [ ]:
# !는 셀에서 실행할때 , pip = python install package

In [3]:
import numpy as np

In [6]:
import numpy as np

data1 = [0, 1, 2, 3, 4, 5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [7]:
data2 = [0.1, 5, 4, 12, 0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [9]:
data3 = [5, 4, 12, 0.5, 0.1]
a3 = np.array(data3)
a3

array([ 5. ,  4. , 12. ,  0.5,  0.1])

In [10]:
a1.dtype

dtype('int32')

In [11]:
a2.dtype

dtype('float64')

In [12]:
np.array([0.5, 2, 0.01, 8])

array([0.5 , 2.  , 0.01, 8.  ])

In [18]:
np.array([0.5, 2, 0.01, 8])   # 1차원

array([0.5 , 2.  , 0.01, 8.  ])

In [28]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])    # 2차원

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
a[1,1]

5

In [22]:
np.array([[0.1,2,3], [4,5,0.06], [7,8,9]])

array([[0.1 , 2.  , 3.  ],
       [4.  , 5.  , 0.06],
       [7.  , 8.  , 9.  ]])

### 범위를 지정해 배열 생성

In [29]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [31]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [33]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [36]:
np.arange(11).reshape(4,3)      # 갯수가 맞지 않으면 오류가 걸린다.

ValueError: cannot reshape array of size 11 into shape (4,3)

In [1]:
# ndarray = number dimension array

In [6]:
b2 = np.arange(5)
b2.shape

(5,)

In [7]:
# 튜플은 값 하나를 가지고 있으면 ex) ( 5,) 처럼 끝에 ,를 찍어줘야 한다.

In [11]:
np.linspace(1, 10, 10)   #  np.linspace

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [12]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

### 특별한 형태의 배열 생성

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 배열의 데이터 타입 변환

In [18]:
np.array(['1.5', '0.62', '2', '3.14', '3.141592'])

array(['1.5', '0.62', '2', '3.14', '3.141592'], dtype='<U8')

In [19]:
str_a1 = np.array(['1.567', '0.123', '5.123', '9', '8'])
num_a1 = str_a1.astype(float)
num_a1

array([1.567, 0.123, 5.123, 9.   , 8.   ])

In [20]:
str_a1.dtype

dtype('<U5')

In [21]:
num_a1.dtype

dtype('float64')

In [22]:
str_a2 = np.array(['1', '3', '5', '7', '9'])
num_a2 = str_a2.astype(int)
num_a2

array([1, 3, 5, 7, 9])

In [23]:
str_a2.dtype

dtype('<U1')

In [24]:
num_a2.dtype

dtype('int32')

In [25]:
num_f1 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i1 = num_f1.astype(int)
num_i1

array([10, 21,  0,  4,  5])

In [26]:
num_f1.dtype

dtype('float64')

In [27]:
num_i1.dtype

dtype('int32')

In [28]:
num_f5 = np.array([10, 21, 0.549, 4.75, 5.98])
num_i5 = num_f5.astype(str)
num_i5

array(['10.0', '21.0', '0.549', '4.75', '5.98'], dtype='<U32')

### 난수 배열의 생성

In [29]:
np.random.rand(2,3)

array([[0.30673815, 0.82726135, 0.55042412],
       [0.4766255 , 0.47434065, 0.9383692 ]])

In [30]:
np.random.rand()

0.21288012097707287

In [31]:
np.random.rand(2,3,4)    # 3행 4열 짜리 행렬이 2개가 생성된다.

array([[[0.03623415, 0.6648203 , 0.82812355, 0.33118411],
        [0.21160247, 0.33497943, 0.49887283, 0.35896126],
        [0.29149695, 0.0320884 , 0.00569982, 0.87329991]],

       [[0.61560774, 0.05495077, 0.63711357, 0.40404371],
        [0.24031257, 0.40442732, 0.91006098, 0.45793102],
        [0.78363021, 0.75438369, 0.57784261, 0.17756777]]])

In [44]:
np.random.randint(10, size=(3,4))

array([[2, 2, 4, 6],
       [4, 8, 3, 9],
       [0, 6, 4, 0]])

In [35]:
np.random.randint(1, 30)

8

### 배열의 연산

#### 기본 연산

In [45]:
arr1 = np.array([10, 20, 30, 40])
arr2 = np.array([1, 2, 3, 4])

In [46]:
arr1 + arr2

array([11, 22, 33, 44])

In [48]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [49]:
arr2*2

array([2, 4, 6, 8])

In [50]:
arr2**2

array([ 1,  4,  9, 16], dtype=int32)

In [51]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [52]:
arr1 /arr2

array([10., 10., 10., 10.])

In [53]:
arr1 / (arr2 ** 2)

array([10.        ,  5.        ,  3.33333333,  2.5       ])

In [54]:
arr1 > 20

array([False, False,  True,  True])

#### 통계를 위한 연산

In [56]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [57]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

In [58]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

In [59]:
[arr3.min(), arr3.max()]

[0, 4]

In [60]:
arr4 = np.arange(1,5)
arr4

array([1, 2, 3, 4])

In [61]:
arr4.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [62]:
arr4.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

#### 행렬 연산

In [64]:
A = np.array([0, 1, 2, 3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [65]:
B = np.array([3, 2, 0, 1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

In [66]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [67]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

In [68]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [69]:
A.transpose()

array([[0, 2],
       [1, 3]])

In [70]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [71]:
np.linalg.det(A)

-2.0

### 배열의 인덱싱과 슬라이싱

#### 배열의 인덱싱

In [72]:
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [73]:
a1[0]

0

In [74]:
a1[4]

40

In [75]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [76]:
a1[[1,3,4]]

array([10, 30, 40])

In [77]:
a2 = np.arange(10, 100, 10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [78]:
a2[0,2]

30

In [79]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [80]:
a2[1]

array([40, 50, 60])

In [81]:
a2[1] = np.array([45, 55, 65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

In [82]:
a2[1] = [47, 57, 67]
a2

array([[10, 20, 30],
       [47, 57, 67],
       [70, 80, 95]])

In [83]:
a2[[0, 2], [0, 1]]

array([10, 80])

In [84]:
a = np.array([1, 2, 3, 4, 5, 6])
a[a > 3]

array([4, 5, 6])

In [87]:
a[(a % 2) == 0]

array([2, 4, 6])

#### 배열의 슬라이싱

In [88]:
b1 = np.array([0, 10, 20, 30, 40, 50])
b1[1:4]

array([10, 20, 30])

In [89]:
b1[:3]

array([ 0, 10, 20])

In [90]:
b1[2:]

array([20, 30, 40, 50])

In [92]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [93]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

In [94]:
b2 = np.arange(10, 100, 10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [95]:
b2[1:3, 1:3]    # 여기서 3은 미만이다!!!!

array([[50, 60],
       [80, 90]])

In [96]:
b2[:3, 1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

In [97]:
b2[1][0:2]

array([40, 50])

In [100]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])